Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.name = "playground"
  end
  config.vm.box = "centos/7"
  config.vm.provision "shell", path: "bootstrap-centos-docker.sh", privileged: false
  config.vm.network :forwarded_port, guest: 8080, host: 8080
  config.vm.network "public_network"
end